# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "pseudolang"
version = "0.0.1"
edition = "2021"
description = "A pseudolang interpreter written in Rust"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=x86_64-linux-gnu-gcc"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "linker=x86_64-apple-darwin15-clang"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
cross="0.2.5"
rand = "0.8.5"
